services:
  gitlab:
    image: yrzr/gitlab-ce-arm64v8
    platform: linux/arm64
    ports:
      - "80:80"
      - "2222:22"
    volumes:
      - gitlab-config:/etc/gitlab
      - gitlab-logs:/var/log/gitlab
      - gitlab-data:/var/opt/gitlab
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://localhost';
        gitlab_rails['gitlab_shell_ssh_port'] = 2222;
        nginx['listen_port'] = 80;
        gitlab_workhorse['listen_network'] = 'tcp';
        gitlab_workhorse['listen_addr'] = '0.0.0.0:80';
        unicorn['enable'] = false;
        puma['enable'] = true;
        postgresql['shared_buffers'] = "256MB";
    shm_size: "256m"
    restart: unless-stopped

volumes:
  gitlab-config:
  gitlab-logs:
  gitlab-data:
