services:
  - type: web
    runtime: docker
    name: gitlab
    dockerfilePath: ./Dockerfile
    disk:
      name: gitlab-data
      mountPath: /var/opt/gitlab
      sizeGB: 10
    envVars:
      - key: GITLAB_OMNIBUS_CONFIG
        value: "external_url 'http://0.0.0.0:10000'; gitlab_workhorse['listen_network'] = 'tcp'; gitlab_workhorse['listen_addr'] = '0.0.0.0:10000';"
      - key: PORT
        value: 10000
      - key: GITLAB_ROOT_PASSWORD
        sync: false
    healthCheckPath: /-/health
    autoDeploy: false
